name: ZoneEnchantments
version: 1.2
description: Custom Enchants for Skyblock Zone.
author: Sjalfsvig
main: me.sjalfsvig.zoneenchantments.ZoneEnchantments
depend: [ASkyBlock]
commands:
  sbenchant: